### ISSUE TITLE
bind: Address already in use

### ISSUE THREAD

**Issue by marklrh** [luckydonald/pytg#21] opened 2015-05-22 04:08 UTC
try a simple script and the program warns ``bind: Address already in use`` on stdout. 
````Python
from pytg import Telegram
tg = Telegram(telegram="./tg/bin/telegram-cli",
              pubkey_file="./tg/tg-server.pub")

receiver = tg.receiver
sender = tg.sender

sender.send_photo("xxx", "./yyy.jpg")
````

Does the program correctly close the socket every time when exits?

**Comment by marklrh** [comment] 2015-05-22 04:09
Also, notice simple script like above prints out "terminating currently sending request" twice when exits.

**Comment by luckydonald** [comment] 2015-05-27 11:03
Eh, I am still fighting with closing all sockets in the correct order.
The problem is, the CLI should terminate last, after all the sockets opened by python are closed.
The current situation is:
Whey your python script terminates, the CLI thread get closed by python automatically, already closing the used port. The Sender and the Receiver still have the port open, which will result in locking it up, until the underlying timeout from the OS finally closes it.
Now the duplicating termination is because you can either start the ```Sender``` and/or ```Receiver``` by yourself or included in ```pytg.Telegram```, and must be shut down in both cases.
That currently results in shutting down from the ```Telegram``` CLI part  and afterwards from the ```Sender``` part twice (or ```Receiver```, not quite sure, without the ability to look into it).
This is the currently best way I found working.
If somebody finds a better way, let me know.
After my vacations I will have a look by myself, too.

**Comment by luckydonald** [comment] 2015-05-27 11:08
What I forgot:
The ```bind``` error comes from the CLI subprocess, the ```telegram-cli```. This means there is already that port used.
This can sometimes really be a still running ```telegram-cli```, check that too.

**Comment by luckydonald** [comment] 2015-05-31 10:51
Did that help a bit?

**Comment by marklrh** [comment] 2015-05-31 18:23
that does not help.

**Comment by luckydonald** [comment] 2015-06-03 10:29
which of the above did you try?

**Comment by luckydonald** [comment] 2015-06-09 19:43
Yeah, Anyway, https://github.com/vysheng/tg/pull/606 looks like it could resolve that.

**Closed** 2015-07-02 16:31 UTC
Labels: fixed?

**Comment by luckydonald** [comment] 2015-07-02 16:33
#22

**Comment by vhdmsm** [comment] 2016-03-01 07:48
I still have this issue. It happens when socket is already open and it tries to open another socket while last socket is still open and ```bind: Address already in use``` error shows up and a bit later ```AssertionError: CLI Process died``` error rises and i just should kill the process to make it run again.
